# Site settings
title:       Diego Nogueira
email:       diegoalvareznogueira@gmail.com
author:      Diego Nogueira
description: "Ruby on rails, Scala, linux, e etc."
baseurl:     ""
url:         "http://diegonogueira.com.br"
date_format: "%b %-d, %Y"

# Google services
google_analytics:
google_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: diegonogueira

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments: 
facebook_appid: 
facebook_comments_number: 10

# Social icons
github_username: diegonogueira
bitbucket_username: diegonogueira
stackoverflow_id:
twitter_username: nogueiradiego
google_plus_id: 104313017470857330466
linkedin_username: AAIAAAeZjcgBmriwapU4sUibs65Hc2zvMN4AAbQ
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-paginate
